export const metadata = { title: "Terms", description: "Terms of service." };

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-[76ch] px-6 py-20">
      <p className="text-overline text-muted-foreground">Legal</p>
      <h1 className="text-display-2 mt-3 text-foreground-strong">
        Terms of service
      </h1>
      <p className="text-ui-sm mt-3 text-subtle-foreground">
        Template language. Have counsel review it before relying on it.
      </p>

      <div className="mt-10 space-y-8">
        <section>
          <h2 className="text-title text-foreground-strong">The service</h2>
          <p className="text-body mt-2 text-muted-foreground">
            The service retrieves passages from documents you supply and
            generates answers grounded in them. You retain all rights in your
            documents; we claim none.
          </p>
        </section>

        <section>
          <h2 className="text-title text-foreground-strong">Accuracy</h2>
          <p className="text-body mt-2 text-muted-foreground">
            Answers are generated by a language model and can be wrong. The
            citation and verification features exist to make errors findable, not
            to eliminate them. Do not rely on an answer for a legal, financial,
            medical or safety-critical decision without checking the cited source
            yourself. Published quality metrics describe performance on a stated
            evaluation set and are not a warranty about your corpus.
          </p>
        </section>

        <section>
          <h2 className="text-title text-foreground-strong">Acceptable use</h2>
          <p className="text-body mt-2 text-muted-foreground">
            You are responsible for having the right to upload and process the
            documents you supply, including any personal data they contain.
          </p>
        </section>

        <section>
          <h2 className="text-title text-foreground-strong">Liability</h2>
          <p className="text-body mt-2 text-muted-foreground">
            The service is provided as is. To the extent permitted by law,
            aggregate liability is limited to the fees paid in the twelve months
            preceding the claim.
          </p>
        </section>
      </div>
    </div>
  );
}
